### ISSUE TITLE
Search issues that are unassigned

### ISSUE THREAD

**Issue by ProCode2** [ProCode2/github-search#1]
Currently, the generated URL searches for all issues. Generate a URL that is only searching for issues that are unassigned.

**Comment by Agreon** [comment]
Would love to do this

**Comment by vishal-lokare** [comment]
Can I take this up?

**Comment by ProCode2** [comment]
Hey @Agreon , @vishal-lokare  reached out to me personally and is already took this one up, Sorry for the inconvenience. 

But I would love any additional PRs though. Adding any other functionality such as any other input fields or improve the styling? Feel free to raise an issue @Agreon and I will assign you :).

**Comment by Agreon** [comment]
Okay, no problem. I've already got some ideas :)
